name: med-audio
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1g=h7b6447c_0
  - pip=20.2.2=py38_0
  - python=3.8.5=h7579374_1
  - readline=8.0=h7b6447c_0
  - setuptools=49.6.0=py38_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - appdirs==1.4.4
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.2.0
    - audioread==2.1.8
    - backcall==0.2.0
    - bleach==3.2.1
    - cffi==1.14.2
    - chardet==3.0.4
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.10
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - joblib==0.16.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.1
    - kiwisolver==1.2.0
    - librosa==0.8.0
    - llvmlite==0.34.0
    - markupsafe==1.1.1
    - matplotlib==3.3.2
    - mistune==0.8.4
    - nbclient==0.5.0
    - nbconvert==6.0.5
    - nbformat==5.0.7
    - nest-asyncio==1.4.0
    - notebook==6.1.4
    - numba==0.51.2
    - numpy==1.19.2
    - packaging==20.4
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - pooch==1.2.0
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.7
    - ptyprocess==0.6.0
    - pycparser==2.20
    - pydub==0.25.1
    - pygments==2.7.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pyzmq==19.0.2
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - requests==2.24.0
    - resampy==0.2.2
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - send2trash==1.5.0
    - six==1.15.0
    - soundfile==0.10.3.post1
    - terminado==0.9.1
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tornado==6.0.4
    - traitlets==5.0.4
    - urllib3==1.25.10
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: /home/asabra/anaconda3/envs/med-audio
